require "look_like/version"
require "look_like/matcher"
require "look_like/array-matcher"
require "look_like/nested-array-matcher"
require "look_like/matchers"
require "look_like/rspec-matcher"
require "look_like/support"

require "look_like/matchers/any-value"
require "look_like/matchers/string"
require "look_like/matchers/email"
require "look_like/matchers/enum"
require "look_like/matchers/url"
require "look_like/matchers/regex"
require "look_like/matchers/formatted-number"
require "look_like/matchers/amount"
require "look_like/matchers/number"

