require "look_like/version"
require "look_like/matcher"
require "look_like/array-matcher"
require "look_like/nested-array-matcher"
require "look_like/matchers"
require "look_like/rspec-matcher"
require "look_like/support"

require "look_like/matchers/unkown-matcher"
require "look_like/matchers/equality"
require "look_like/matchers/wildcard"
require "look_like/matchers/string"
require "look_like/matchers/email"
require "look_like/matchers/enum"
require "look_like/matchers/time-stamp"
require "look_like/matchers/date"
require "look_like/matchers/url"
require "look_like/matchers/regex"
require "look_like/matchers/formatted-number"
require "look_like/matchers/amount"
require "look_like/matchers/number"
require "look_like/matchers/integer"
require "look_like/matchers/negative-integer"

